checkerboards:
  cb_9x6: {corners_x: 0, corners_y: 0, spacing_x: 0, spacing_y: 0}
dh_chains:
  arm_chain:
    cov:
      joint_angles: [0, 0, 0, 0, 0, 0, 0]
  torso_chain:
    cov:
      joint_angles: [0, 0, 0]
rectified_cams:
  kinect_rgb:
    baseline_shift: 0
    cov: {u: 0, v: 0}
    cx_shift: 0
    cy_shift: 0
    f_shift: 0
  left:
    baseline_shift: 0
    cov: {u: 0, v: 0}
    cx_shift: 0
    cy_shift: 0
    f_shift: 0
  right:
    baseline_shift: 0
    cov: {u: 0, v: 0}
    cx_shift: 0
    cy_shift: 0
    f_shift: 0
transforms:
  arm_0_link: [0, 0, 0, 0, 0, 0]
  arm_cb: [0, 0, 0, 0, 0, 0]
  head_cam3d_frame: [0, 0, 0, 0, 0, 0]
  head_color_camera_l_frame: [0, 0, 0, 0, 0, 0]
  head_cover_link: [0, 0, 0, 0, 0, 0]
  sdh_palm_link: [0, 0, 0, 0, 0, 0]
  torso_0_link: [0, 0, 0, 0, 0, 0]
