checkerboards:
  cb_9x6: {corners_x: 9, corners_y: 6, spacing_x: 0.029999999999999999, spacing_y: 0.029999999999999999}
dh_chains:
  arm_chain:
    cov:
      joint_angles: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  torso_chain:
    cov:
      joint_angles: [0.01, 0.01, 0.01]
rectified_cams:
  kinect_rgb:
    baseline_shift: 0.0
    cov: {u: 0.25, v: 0.25}
    cx_shift: 0.0
    cy_shift: 0.0
    f_shift: 0.0
  left:
    baseline_shift: 0.0
    cov: {u: 0.125, v: 0.125}
    cx_shift: 0.0
    cy_shift: 0.0
    f_shift: 0.0
  right:
    baseline_shift: 0.0
    cov: {u: 0.125, v: 0.125}
    cx_shift: 0.0
    cy_shift: 0.0
    f_shift: 0.0
transforms:
  arm_0_link: [0.040000000000000001, -0.0050000000000000001, 0.83640000000000003,
    3.1415999999999999, 0.78539999999999999, -1.8326]
  arm_cb: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  head_cam3d_frame: [-0.050000000000000003, -0.040000000000000001, -0.01, -1.5708,
    0.0, 3.1415999999999999]
  head_color_camera_l_frame: [-0.035000000000000003, -0.0064999999999999997, -0.059999999999999998,
    -1.5708, 0.0, 3.1415999999999999]
  head_cover_link: [0.0, 0.0, 0.0, -3.1415999999999999, -0.0, 0.0]
  sdh_palm_link: [0.0, 0.0, 0.0, 3.1415999999999999, -0.0, 3.1415999999999999]
  torso_0_link: [0.16, 0.0, 0.874, 1.5708, -0.0, 0.0]
